name: sohail_auto
description: "A project that make me undersatnd what the people understand me"

publish_to: 'none'


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.0
  hive: ^2.2.3
  get: ^4.7.2
  hive_flutter: ^1.1.0
  pdf: ^3.10.7
  printing: ^5.11.0
  intl: ^0.20.2
  uuid: ^4.0.0
  flutter_svg: ^2.2.0
  flutter_native_splash: ^2.4.6
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.9.1
  permission_handler: ^12.0.1
  file_picker: ^10.2.0
  animated_custom_dropdown: ^3.1.1
  flutter_spinkit: ^5.2.1
  device_frame: ^1.4.0
  flutter_animate: ^4.5.2
  table_calendar: ^3.2.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  device_frame_plus: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Lufga
      fonts:
            - asset: assets/fonts/LufgaBlack.ttf
              weight: 900
            - asset: assets/fonts/LufgaBold.ttf
              weight: 700
            - asset: assets/fonts/LufgaSemiBold.ttf
              weight: 600
            - asset: assets/fonts/LufgaMedium.ttf
              weight: 500
            - asset: assets/fonts/LufgaRegular.ttf
              weight: 400

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


